[package]
name = "discord-ci-cd"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
poise = "0.6.1"
serde = { version = "1.0.204", features = ["derive"] }
tokio = { version = "1.39.2", features = ["full"] }
url = { version = "2.5.2", features = ["serde"] }
