[package]
name = "discord-ci-cd"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.13", features = ["derive"] }
poise = "0.6.1"
serenity = "0.12.2"
tokio = { version = "1.39.2", features = ["full"] }
url = { version = "2.5.2", features = ["serde"] }
